// Automatically generated by scripts/generate-style-registries.js
// Do not edit this file manually.

import React from "react"
import BottomNavBarStyle1 from "./styles/style-1"
import BottomNavBarStyle2 from "./styles/style-2"
import BottomNavBarStyle3 from "./styles/style-3"

export const STYLES: Record<string, React.ComponentType<any>> = {
  "style-1": BottomNavBarStyle1,
  "style-2": BottomNavBarStyle2,
  "style-3": BottomNavBarStyle3,
}
