// Automatically generated by scripts/generate-style-registries.js
// Do not edit this file manually.

import React from "react";
import PageTransitionStyle1 from "./styles/style-1";
import PageTransitionStyle2 from "./styles/style-2";
import PageTransitionStyle3 from "./styles/style-3";
import PageTransitionStyle4 from "./styles/style-4";

export const STYLES: Record<string, React.ComponentType<any>> = {
  "style-1": PageTransitionStyle1,
  "style-2": PageTransitionStyle2,
  "style-3": PageTransitionStyle3,
  "style-4": PageTransitionStyle4,
};
