// Automatically generated by scripts/generate-style-registries.js
// Do not edit this file manually.

import React from "react"
import ProductShowcaseStyle1 from "./styles/style-1"
import ProductShowcaseStyle2 from "./styles/style-2"

export const STYLES: Record<string, React.ComponentType<any>> = {
  "style-1": ProductShowcaseStyle1,
  "style-2": ProductShowcaseStyle2,
}
