// Automatically generated by scripts/generate-style-registries.js
// Do not edit this file manually.

import React from "react"
import BlockHeaderStyle1 from "./styles/style-1"
import BlockHeaderStyle2 from "./styles/style-2"
import BlockHeaderStyle3 from "./styles/style-3"

export const STYLES: Record<string, React.ComponentType<any>> = {
  "style-1": BlockHeaderStyle1,
  "style-2": BlockHeaderStyle2,
  "style-3": BlockHeaderStyle3,
}
