// Automatically generated by scripts/generate-style-registries.js
// Do not edit this file manually.

import React from "react"
import FeaturesBlockStyle1 from "./styles/style-1"
import FeaturesBlockStyle2 from "./styles/style-2"
import FeaturesBlockStyle3 from "./styles/style-3"
import FeaturesBlockStyle4 from "./styles/style-4"

export const STYLES: Record<string, React.ComponentType<any>> = {
  "style-1": FeaturesBlockStyle1,
  "style-2": FeaturesBlockStyle2,
  "style-3": FeaturesBlockStyle3,
  "style-4": FeaturesBlockStyle4,
}
