// Automatically generated by scripts/generate-style-registries.js
// Do not edit this file manually.

import React from "react";
import ProfileStyle1 from "./styles/style-1";
import ProfileStyle2 from "./styles/style-2";

export const STYLES: Record<string, React.ComponentType<any>> = {
  "style-1": ProfileStyle1,
  "style-2": ProfileStyle2,
};


// --- PROFILE COMPONENTS AUTO-GENERATED ---
import SharedAddressBook from "./components/address-book";
import SharedReturnItemSelector from "./components/return-item-selector";
import SharedReturnShippingSelector from "./components/return-shipping-selector";
import SharedWishlistOverview from "./components/wishlist-overview";
import Style1AccountInfo from "./styles/style-1/components/account-info";
import Style1AccountNav from "./styles/style-1/components/account-nav";
import Style1OrderCard from "./styles/style-1/components/order-card";
import Style1OrderDetails from "./styles/style-1/components/order-details";
import Style1OrderOverview from "./styles/style-1/components/order-overview";
import Style1OrdersDetails from "./styles/style-1/components/orders-details";
import Style1Overview from "./styles/style-1/components/overview";
import Style1ProfileBillingAddress from "./styles/style-1/components/profile-billing-address";
import Style1ProfileDetails from "./styles/style-1/components/profile-details";
import Style1ProfileEmail from "./styles/style-1/components/profile-email";
import Style1ProfileName from "./styles/style-1/components/profile-name";
import Style1ProfilePassword from "./styles/style-1/components/profile-password";
import Style1ProfilePhone from "./styles/style-1/components/profile-phone";
import Style1ProfileUsername from "./styles/style-1/components/profile-username";
import Style1TransferRequestForm from "./styles/style-1/components/transfer-request-form";
import Style2AccountInfo from "./styles/style-2/components/account-info";
import Style2AccountNav from "./styles/style-2/components/account-nav";
import Style2OrderCard from "./styles/style-2/components/order-card";
import Style2OrderDetails from "./styles/style-2/components/order-details";
import Style2OrderOverview from "./styles/style-2/components/order-overview";
import Style2OrdersDetails from "./styles/style-2/components/orders-details";
import Style2Overview from "./styles/style-2/components/overview";
import Style2ProfileBillingAddress from "./styles/style-2/components/profile-billing-address";
import Style2ProfileDetails from "./styles/style-2/components/profile-details";
import Style2ProfileEmail from "./styles/style-2/components/profile-email";
import Style2ProfileName from "./styles/style-2/components/profile-name";
import Style2ProfilePassword from "./styles/style-2/components/profile-password";
import Style2ProfilePhone from "./styles/style-2/components/profile-phone";
import Style2ProfileUsername from "./styles/style-2/components/profile-username";
import Style2TransferRequestForm from "./styles/style-2/components/transfer-request-form";

export const SHARED_PROFILE_COMPONENTS: Record<string, React.ComponentType<any>> = {
  "address-book": SharedAddressBook,
  "return-item-selector": SharedReturnItemSelector,
  "return-shipping-selector": SharedReturnShippingSelector,
  "wishlist-overview": SharedWishlistOverview,
};

export const STYLE_PROFILE_COMPONENTS: Record<string, Record<string, React.ComponentType<any>>> = {
  "style-1": {
    "account-info": Style1AccountInfo,
    "account-nav": Style1AccountNav,
    "order-card": Style1OrderCard,
    "order-details": Style1OrderDetails,
    "order-overview": Style1OrderOverview,
    "orders-details": Style1OrdersDetails,
    "overview": Style1Overview,
    "profile-billing-address": Style1ProfileBillingAddress,
    "profile-details": Style1ProfileDetails,
    "profile-email": Style1ProfileEmail,
    "profile-name": Style1ProfileName,
    "profile-password": Style1ProfilePassword,
    "profile-phone": Style1ProfilePhone,
    "profile-username": Style1ProfileUsername,
    "transfer-request-form": Style1TransferRequestForm,
  },
  "style-2": {
    "account-info": Style2AccountInfo,
    "account-nav": Style2AccountNav,
    "order-card": Style2OrderCard,
    "order-details": Style2OrderDetails,
    "order-overview": Style2OrderOverview,
    "orders-details": Style2OrdersDetails,
    "overview": Style2Overview,
    "profile-billing-address": Style2ProfileBillingAddress,
    "profile-details": Style2ProfileDetails,
    "profile-email": Style2ProfileEmail,
    "profile-name": Style2ProfileName,
    "profile-password": Style2ProfilePassword,
    "profile-phone": Style2ProfilePhone,
    "profile-username": Style2ProfileUsername,
    "transfer-request-form": Style2TransferRequestForm,
  },
};
