// Automatically generated by scripts/generate-style-registries.js
// Do not edit this file manually.

import React from "react";
import FooterStyle1 from "./styles/style-1";
import FooterStyle2 from "./styles/style-2";

export const STYLES: Record<string, React.ComponentType<any>> = {
  "style-1": FooterStyle1,
  "style-2": FooterStyle2,
};
