// Automatically generated by scripts/generate-style-registries.js
// Do not edit this file manually.

import React from "react"
import SplitBannerStageStyle1 from "./styles/style-1"
import SplitBannerStageStyle2 from "./styles/style-2"

export const STYLES: Record<string, React.ComponentType<any>> = {
  "style-1": SplitBannerStageStyle1,
  "style-2": SplitBannerStageStyle2,
}
