// Automatically generated by scripts/generate-style-registries.js
// Do not edit this file manually.

import React from "react";
import LoginStyle1 from "./styles/style-1";
import LoginStyle2 from "./styles/style-2";
import LoginStyle3 from "./styles/style-3";

export const STYLES: Record<string, React.ComponentType<any>> = {
  "style-1": LoginStyle1,
  "style-2": LoginStyle2,
  "style-3": LoginStyle3,
};
