// Automatically generated by scripts/generate-style-registries.js
// Do not edit this file manually.

import React from "react"
import TemplatesStyle1 from "./styles/style-1"
import TemplatesStyle1Summary from "./styles/style-1/summary"
import TemplatesStyle2 from "./styles/style-2"

export const STYLES: Record<string, React.ComponentType<any>> = {
  "style-1": TemplatesStyle1,
  "style-2": TemplatesStyle2,
}

export const SUMMARY_STYLES: Record<string, React.ComponentType<any>> = {
  "style-1": TemplatesStyle1Summary,
}
