// Automatically generated by scripts/generate-style-registries.js
// Do not edit this file manually.

import React from "react";
import CategoryCollectionShowcaseStyle1 from "./styles/style-1";
import CategoryCollectionShowcaseStyle2 from "./styles/style-2";
import CategoryCollectionShowcaseStyle3 from "./styles/style-3";

export const STYLES: Record<string, React.ComponentType<any>> = {
  "style-1": CategoryCollectionShowcaseStyle1,
  "style-2": CategoryCollectionShowcaseStyle2,
  "style-3": CategoryCollectionShowcaseStyle3,
};
