// Automatically generated by scripts/generate-style-registries.js
// Do not edit this file manually.

import React from "react"
import HeaderStyle1 from "./styles/style-1"
import HeaderStyle2 from "./styles/style-2"
import HeaderStyle3 from "./styles/style-3"

export const STYLES: Record<string, React.ComponentType<any>> = {
  "style-1": HeaderStyle1,
  "style-2": HeaderStyle2,
  "style-3": HeaderStyle3,
}
