// Automatically generated by scripts/generate-style-registries.js
// Do not edit this file manually.

import React from "react"
import HeroStyle1 from "./styles/style-1"

export const STYLES: Record<string, React.ComponentType<any>> = {
  "style-1": HeroStyle1,
}
